### PR TITLE
FIX: NODE-SECURITY-813: js-yaml < 3.13.1 code injection

### LINKED ISSUE #183: Code injection security vulnerability at js-yaml
Hi there,

Thanks for making cosmiconfig!

You have a dependency on `js-yaml@3.13.0`. Please see this report of a High severity vulnerability in this module.

https://www.npmjs.com/advisories/813

### PR DESCRIPTION
**Pull request by zzak**
Addresses the following [CVE](https://www.npmjs.com/advisories/813).

Edit: Closes #183

### CODE REVIEW

**Comment by olsonpm** [comment]
Hi @zzak - thanks for the PR, however this project uses `yarn` and your commit modifies package.json only.  Would you mind running `yarn add js-yaml@^3.13.1` ?  The resulting diff should be

```diff
diff --git a/package.json b/package.json
index 4be32f8..814762c 100644
--- a/package.json
+++ b/package.json
@@ -85,7 +85,7 @@
   "dependencies": {
     "import-fresh": "^2.0.0",
     "is-directory": "^0.3.1",
-    "js-yaml": "^3.13.0",
+    "js-yaml": "^3.13.1",
     "parse-json": "^4.0.0"
   },
   "devDependencies": {
diff --git a/yarn.lock b/yarn.lock
index 276c3a8..96546bc 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -2410,10 +2410,10 @@ js-tokens@^3.0.0, js-tokens@^3.0.2:
   version "3.0.2"
   resolved "https://registry.yarnpkg.com/js-tokens/-/js-tokens-3.0.2.tgz#9866df395102130e38f7f996bceb65443209c25b"
 
-js-yaml@^3.13.0:
-  version "3.13.0"
-  resolved "https://registry.yarnpkg.com/js-yaml/-/js-yaml-3.13.0.tgz#38ee7178ac0eea2c97ff6d96fff4b18c7d8cf98e"
-  integrity sha512-pZZoSxcCYco+DIKBTimr67J6Hy+EYGZDY/HCWC+iAEA9h1ByhMXAIVUXMcMFpOCxQ/xjXmPI2MkDL5HRm5eFrQ==
+js-yaml@^3.13.1:
+  version "3.13.1"
+  resolved "https://registry.yarnpkg.com/js-yaml/-/js-yaml-3.13.1.tgz#aff151b30bfdfa8e49e05da22e7415e9dfa37847"
+  integrity sha512-YfbcO7jXDdyj0DGxYVSlSeQNHbD7XPWvrVWeVUujrQEoZzWJIRrCPoyk6kL6IAjAG2IolMK4T0hNUe0HOUs5Jw==
   dependencies:
     argparse "^1.0.7"
     esprima "^4.0.0"
```

**Comment by pcezanne** [comment]
It looks like this hasn't been merged? Is there something else that needs to be addressed?

**Comment by davidtheclark** [comment]
Done in 240aaa759fed016bf0e3950d62234f4c2aab0ce5, released in 5.2.1.

**Comment by zzak** [comment]
@olsonpm @davidtheclark Thanks for taking care of this! Sorry for not following up :bow:

**Comment by olsonpm** [comment]
not a problem at all

**Pull request closed without merging**
