### PR TITLE
Switch from tape to ava

### PR DESCRIPTION
**Pull request by davidtheclark**
This was primarily for the sake of experimenting with [ava](https://github.com/sindresorhus/ava) -- but I think it's actually better, because the Promise support of ava leads to cleaner tests for this Promise-heavy project (no need to count assertions). @TrySound what do you think?

### CODE REVIEW

**Comment by davidtheclark** [comment]
I have no idea why only Node 0.10 is complaining about a bunch of `Unhandled Rejection`s --- when they are in fact handled by `.catch()` statements.

**Comment by TrySound** [comment]
@davidtheclark Why they are serial?

**Comment by TrySound** [comment]
@davidtheclark Success :)

**Comment by davidtheclark** [comment]
@TrySound They had to be serial because of the way that I'm stubbing `fs` each time. If I don't mark them as serial, one starts and stubs `fs`, then another starts and tries to stub what's already stubbed. I'm open to another way of stubbing/mocking `fs`; but this way works for now.

**Comment by TrySound** [comment]
@davidtheclark Okay

**Comment by TrySound** [comment]
@davidtheclark Hey, where's ci?

**Comment by davidtheclark** [comment]
@TrySound ?? Looks like it passed

**Comment by TrySound** [comment]
@davidtheclark Yep. Just was big delay. But pinkie is buggy :(

**Comment by davidtheclark** [comment]
@TrySound So I don't have any other plans currently. Do you? Or are we ready for a 1.0.0 release?

**Comment by TrySound** [comment]
@davidtheclark I want to try to understand why pinkie doesn't work. It's just on my computer and appveyor

**Comment by TrySound** [comment]
@davidtheclark Okay, seems like it's windows hello.

**Comment by TrySound** [comment]
@davidtheclark I'm not ready for new plans :)) We can make patches if something will go wrong.

**Comment by davidtheclark** [comment]
Ok. Yeah, we might have bugs but I think the API looks good. Sometime later today or tomorrow I will take another look at the docs and then release.

**Comment by MoOx** [comment]
\o/

**Comment by davidtheclark** [comment]
Released!

**Comment by TrySound** [comment]
Cool!

**Pull request merged**
