### PR TITLE
Added cjs support

### PR DESCRIPTION
**Pull request by k2snowman69**

### CODE REVIEW

**Comment by k2snowman69** [comment]
If anyone has comments (other than the CI failing) ony PR let me know. I'll try to get the CI cleaned up by Sunday evening.

**Comment by k2snowman69** [comment]
Failing PRs seem to be due to semver not supporting node 8 anymore. I'll leave it to the owner of the package to determine how they wish to resolve this issue.

**Comment by davidtheclark** [comment]
Following up on https://github.com/davidtheclark/cosmiconfig/issues/224#issuecomment-657294007, I changed the base branch of this PR to `v7`. Can you please rebase off that branch? It should fix the CI problems.

**Comment by davidtheclark** [comment]
Also: want to add some documentation about the new feature?

**Comment by k2snowman69** [comment]
I was hesitant to add documentation since it's technically only a partial fix to support ESM instead of full support. If you'd like me to I can, but it maybe faster for you to add it since you know how you'd like to display/organize such partial implementation information.

**Comment by davidtheclark** [comment]
> it maybe faster for you to add it since you know how you'd like to display/organize such partial implementation information

I would just add `.cjs` to all the lists of default search places in the readme.

You can also add a changelog note. Or I can add that later.

**Comment by k2snowman69** [comment]
I can do the readme. I'll leave the changelog for you since you can bucket all the new ESM logic in one giant breaking entry

**Comment by k2snowman69** [comment]
Should be good to go, let me know if you see anything else. Again, leaving the changelog for you so you can make a more simplified writeup with the ESM breaking changes all summarized.

**Pull request merged**
