### PR TITLE
Separate readFile promise for better error handling

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by TrySound** [comment]
Do not merge. Want to make it with all loaders. Waiting for success

**Comment by davidtheclark** [comment]
Ah, this technique makes sense to me. I had some struggles figuring out the right way to handle the interface between errors happening in the `readFile` callback and the Promise chain (http://stackoverflow.com/questions/33651306/why-doesnt-promise-catch-error-thrown-by-async-operation). I like the way you are doing it here.

**Comment by TrySound** [comment]
Will make some noise without local tests. )

**Comment by TrySound** [comment]
@davidtheclark  I see eslint config is not quite strict

**Comment by TrySound** [comment]
Seems done. Should I squash all commits?

**Comment by davidtheclark** [comment]
Nah, I haven't been too worried about a clean history during this initial development period.

**Pull request merged**
