### PR TITLE
Updated node engine version

### PR DESCRIPTION
**Pull request by amilajack**
Install will fail with yarn, which correctly checks node engines in `package.json`

```
error cosmiconfig@2.0.1: The engine "node" is incompatible with this module. Expected version "4".
```

### CODE REVIEW

**Comment by amilajack** [comment]
Seems like tests already support it
```
https://github.com/davidtheclark/cosmiconfig/blob/master/.travis.yml#L4
```

**Comment by amilajack** [comment]
Fixes https://github.com/davidtheclark/cosmiconfig/issues/32

**Comment by ChristopherBiscardi** [comment]
heh, scooped me on the PR 😂 Thanks for getting to this @amilajack

**Comment by davidtheclark** [comment]
Thanks! I'll put out a patch release.

**Pull request merged**
