### PR TITLE
Typecheck configPath cli argument. Defer path.resolve call to config lookup runtime.

### PR DESCRIPTION
**Pull request by amiller-gh**
See https://github.com/prettier/prettier/issues/2797 and https://github.com/prettier/prettier/pull/2798 for why this is needed.

### CODE REVIEW

**Comment by davidtheclark** [comment]
Thanks @amiller-gh for investigating.

I feel like it's probably a mistake for cosmiconfig to pay attention to a `--config` argument in `process.argv`. It's just too much of an assumption. This fix solves your very particular problem where the value of `--config` is an array — but it's a pretty specific fix, and I suspect that the more general problem is "cosmiconfig doesn't know enough about your program or its context to cherry pick `process.argv` items."

I'm in favor of removing the `--config` feature altogether. Since we're about to cut a major release (v3), we have a good opportunity. 

@sudo-suhas what do you think?

**Comment by sudo-suhas** [comment]
@davidtheclark I agree. Since cosmiconfig is not meant to be directly invoked from the CLI, makes sense to remove it. The caller can include it in the options if they wish. Would you like me to make a PR for this?

**Comment by davidtheclark** [comment]
@sudo-suhas 👍 go for it.

**Comment by sudo-suhas** [comment]
Okay, will do after #87 is merged in to avoid conflicts.

**Pull request closed without merging**
