### PR TITLE
Revert pinkie

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by TrySound** [comment]
Sorry for noise

**Comment by TrySound** [comment]
@davidtheclark 
https://github.com/sindresorhus/loud-rejection/issues/10#issuecomment-160067870

**Comment by TrySound** [comment]
@davidtheclark Tests are passed. You can publish as a patch :)

**Comment by davidtheclark** [comment]
Thanks for investigating this.

**Pull request merged**
