### PR TITLE
chore: use yarn cache

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by olsonpm** [comment]
is there a reason all these chores are separate PRs?  seems they are all meant to be build improvements and could be lumped together.

**Comment by sudo-suhas** [comment]
I am in agreement with @olsonpm. @DanielRuf Would you mind creating a single PR on the lines of `Tweak CI config` for the 3 PRs? You could keep the commits separate.

**Comment by sudo-suhas** [comment]
Also, the caching for yarn can be added on Appveyor as well. Here's an example PR which does so - okonet/lint-staged#378.

**Comment by DanielRuf** [comment]
Will do so later today. Thanks for the feedback.

**Comment by DanielRuf** [comment]
> Also, the caching for yarn can be added on Appveyor as well.

It is there already, see https://github.com/davidtheclark/cosmiconfig/blob/master/appveyor.yml#L17

This is why I did not update the appveyor config in this case.

**Comment by davidtheclark** [comment]
Replaced by #141.

**Pull request closed without merging**
