### PR TITLE
chore: add Node.js 8 and 10

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by sudo-suhas** [comment]
Hey @DanielRuf, I noticed that you removed node < 8 from the list of versions to test on. However, we have not dropped support for node 4 yet. Since this is a heavily depended upon package, I think we'd want to allow all packages who depend on cosmiconfig to have some more time before we make the breaking change.

**Comment by DanielRuf** [comment]
Ok I'll add them again even if Node.js 4 reached its EOL.

**Comment by DanielRuf** [comment]
Done.

**Comment by davidtheclark** [comment]
Replaced by #141.

**Pull request closed without merging**
